### ISSUE TITLE
UltraVNC

### ISSUE THREAD

**Issue by Neustradamus** [AlbanAndrieu/ansible-windows#1]
Hello @AlbanAndrieu,

UltraVNC is very old here, it is possible to update?
- https://github.com/AlbanAndrieu/ansible-windows/blob/master/files/workstation-packages.config#L35

Latest UltraVNC build is here:
- https://forum.uvnc.com/viewforum.php?f=56

Thanks in advance.

**Comment by AlbanAndrieu** [comment]
Hi @Neustradamus ,
No pb, feel free to create a Pull request and I will approve it
